import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    include: ['scripts/tests/**/*.test.js'],
    coverage: {
      provider: 'v8',
      include: [
        'scripts/convert.mjs',
        'scripts/generate-manifest.mjs',
        'scripts/sync-knowledge.mjs',
        'functions/api/chat.js',
        'functions/api/transform.js',
        'functions/api/webhooks.js',
        'functions/api/tokens.js',
        'functions/api/health.js',
        'functions/api/logs.js',
        'functions/api/rate_limiter_do.js',
        'functions/api/webhook_consumer.js',
        'functions/api/assets.js',
        'functions/api/search.js',
        'functions/api/signed.js',
        'functions/api/pipeline.js',
        'functions/api/auto.js',
        // Escape glob brackets so vitest doesn't treat them as a char class.
        'functions/api/storage/\\[\\[path\\]\\].js',
        'functions/api/core/zones.js',
        'functions/api/core/audit-logs.js',
        'functions/api/core/statistics.js',
        'functions/api/insights/asset.js',
        'functions/api/insights/errors.js',
        'functions/api/insights/geography.js',
        'functions/api/insights/summary.js',
        'functions/api/insights/top-assets.js',
        'functions/api/purge.js',
        'functions/api/lqip.js',
        'functions/api/ai/alt-text.js',
        'functions/api/ai/smart-crop.js',
        'functions/api/ai/moderate.js',
        'functions/api/stream.js',
        'functions/api/core/rules.js',
        'functions/api/analytics.js',
        'functions/api/storage/batch.js',
      ],
      all: false,
      thresholds: {
        statements: 100,
        branches: 100,
        functions: 100,
        lines: 100,
      },
    },
  },
});
